- type: bug
  scope: project
  issue_id: f0531a96-1507-49ea-8c43-9d355d290397
  task_id: null
  title: Batch 4 commits partially failed without clear error
  detail: During commit of Batch 4 (fetch_summary feature), the initial commit call
    succeeded only for memory.py, while the remaining files (schemas/summary.py, utils/memory_manager.py,
    clients/airtable_client.py) were not committed despite no explicit error being
    returned. Required manual re-commits. Possibly due to context overrun or file
    buffer handling during bulk updates.
  suggested_fix: Verify commit payload size limits or logging around batch commits
    to ensure atomicity or return more descriptive error messaging.
  tags:
  - commit
  - bug
  - batch
  - file-sync
  status: open
  timestamp: '2025-05-04T02:36:37.097707'
- type: enhancement
  scope: project
  issue_id: 9952c4dc-71c7-4dce-b2c4-2ef4ff5963b6
  task_id: null
  title: Standardize file organization to prevent document sprawl
  detail: "As more tasks commit outputs, we\u2019re seeing similar documents (logs,\
    \ specs, retros, reflections) land in inconsistent folders or custom subpaths.\
    \ This reduces discoverability and increases cognitive load for incoming pods."
  suggested_fix: 'Create and publish a file structure guide for the repo. Encourage
    pods to:

    - Use standardized subfolders: `logs/retrospectives/`, `logs/reflections/`, `specs/`,
    `architecture/`, `testing/`

    - Include a `file_type` tag in metadata to auto-suggest folders

    - Provide a helper tool or hook that checks proposed file paths against existing
    structure and suggests alignment'
  tags:
  - enhancement
  - repo-structure
  - file-paths
  - standards
  - organization
  status: open
  timestamp: '2025-05-05T18:34:48.364731'
- type: enhancement
  scope: project
  issue_id: 3e3a216e-b3de-4294-a83a-efa177d7659d
  task_id: null
  title: Add pre-deployment validation to prevent import and dependency errors
  detail: During Task 2.8, multiple Railway deployment failures were caused by missing
    modules, unresolved imports, and unlisted dependencies. These could have been
    caught earlier by a pre-deploy validation step.
  suggested_fix: 'Introduce a pre-deploy validation script that checks:

    - All route modules import successfully

    - Required environment variables exist

    - Required dependencies (like httpx, pyyaml) are listed in requirements.txt

    - FastAPI app entrypoint is accessible


    This could be implemented as a GitHub Action or local dev script.'
  tags:
  - deployment
  - ci
  - validation
  - infra
  status: open
  timestamp: '2025-05-06T09:32:08.332042'
